name: Build LaTeX document

on:
  push:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Build
        run: make github
      - uses: actions/upload-artifact@v4
        with:
          name: refman
          path: ./*.pdf
